import axiosInstance, { MOCK_MODE } from '../api/axiosConfig';

const MOCK_PRODUCTS = [
  // 1. Vegetables (15 Items)
  {
    id: 'prod-1',
    name: 'Organic Vine Tomatoes',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Vegetables',
    price: 25,
    quantity: 150,
    organic: true,
    rating: 4.8,
    distance: 1.5,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Freshly harvested vine-ripened organic tomatoes from Madanapalle. Chemical-free and rich in flavor.',
    image: 'https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-2',
    name: 'Green Chillies',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Vegetables',
    price: 40,
    quantity: 80,
    organic: true,
    rating: 4.6,
    distance: 1.5,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Spicy organic green chillies, handpicked fresh from Basinikonda village fields.',
    image: 'https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-3',
    name: 'Fresh Lady Finger (Bhindi)',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Vegetables',
    price: 35,
    quantity: 120,
    organic: true,
    rating: 4.5,
    distance: 1.5,
    harvestDate: '2026-07-21',
    freshness: 'High',
    description: 'Tender lady fingers, rich in dietary fiber, harvested fresh.',
    image: 'https://images.pexels.com/photos/2583187/pexels-photo-2583187.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-4',
    name: 'Organic Red Onions',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Vegetables',
    price: 30,
    quantity: 200,
    organic: true,
    rating: 4.7,
    distance: 1.5,
    harvestDate: '2026-07-20',
    freshness: 'High',
    description: 'Crisp red onions harvested with zero synthetic pesticides.',
    image: 'https://images.pexels.com/photos/1443867/pexels-photo-1443867.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-5',
    name: 'Fresh Potatoes',
    farmerName: 'Kishore Kumar',
    farmerId: 'f-4',
    farmName: 'Ananthapuram Paddy Fields',
    category: 'Vegetables',
    price: 28,
    quantity: 300,
    organic: false,
    rating: 4.4,
    distance: 6.5,
    harvestDate: '2026-07-19',
    freshness: 'High',
    description: 'Starchy daily essential potatoes sorted directly from fields.',
    image: 'https://images.pexels.com/photos/2286777/pexels-photo-2286777.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-6',
    name: 'Orange Carrots',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Vegetables',
    price: 50,
    quantity: 90,
    organic: true,
    rating: 4.8,
    distance: 1.5,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Sweet and crunchy carrots packed with Beta-Carotene.',
    image: 'https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-7',
    name: 'Green Cauliflower',
    farmerName: 'Saraswathi Devi',
    farmerId: 'f-3',
    farmName: 'Saraswathi Greens',
    category: 'Vegetables',
    price: 45,
    quantity: 70,
    organic: true,
    rating: 4.6,
    distance: 8.4,
    harvestDate: '2026-07-21',
    freshness: 'High',
    description: 'Nutritious green cauliflower heads harvested locally.',
    image: 'https://images.pexels.com/photos/461271/pexels-photo-461271.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-8',
    name: 'Organic Capsicum (Green)',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Vegetables',
    price: 60,
    quantity: 100,
    organic: true,
    rating: 4.7,
    distance: 1.5,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Crisp green bell peppers grown inside polyhouse greenhouse frames.',
    image: 'https://images.pexels.com/photos/2893635/pexels-photo-2893635.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-9',
    name: 'Fresh Eggplant (Brinjal)',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Vegetables',
    price: 32,
    quantity: 130,
    organic: true,
    rating: 4.5,
    distance: 1.5,
    harvestDate: '2026-07-21',
    freshness: 'High',
    description: 'Glossy purple local brinjals perfect for traditional curries.',
    image: 'https://images.pexels.com/photos/321552/pexels-photo-321552.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-10',
    name: 'Leafy Spinach (Palak)',
    farmerName: 'Saraswathi Devi',
    farmerId: 'f-3',
    farmName: 'Saraswathi Greens',
    category: 'Vegetables',
    price: 20,
    quantity: 80,
    organic: true,
    rating: 4.9,
    distance: 8.4,
    harvestDate: '2026-07-22',
    freshness: 'Excellent',
    description: 'Iron-rich freshly cut local spinach leaves washed with clean water.',
    image: 'https://images.pexels.com/photos/2325843/pexels-photo-2325843.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-11',
    name: 'Coriander Bunches',
    farmerName: 'Saraswathi Devi',
    farmerId: 'f-3',
    farmName: 'Saraswathi Greens',
    category: 'Vegetables',
    price: 15,
    quantity: 150,
    organic: true,
    rating: 4.8,
    distance: 8.4,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Aromatic green coriander leaves harvested fresh every morning.',
    image: 'https://images.pexels.com/photos/1081015/pexels-photo-1081015.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-12',
    name: 'Bitter Gourd (Karela)',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Vegetables',
    price: 38,
    quantity: 90,
    organic: true,
    rating: 4.4,
    distance: 1.5,
    harvestDate: '2026-07-20',
    freshness: 'High',
    description: 'Organic bitter gourd, rich in antioxidants, excellent for health.',
    image: 'https://images.pexels.com/photos/5945903/pexels-photo-5945903.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-13',
    name: 'Fresh Garlic Plugs',
    farmerName: 'Kishore Kumar',
    farmerId: 'f-4',
    farmName: 'Ananthapuram Paddy Fields',
    category: 'Vegetables',
    price: 120,
    quantity: 100,
    organic: false,
    rating: 4.5,
    distance: 6.5,
    harvestDate: '2026-07-15',
    freshness: 'High',
    description: 'Dried garlic bulbs sorted directly from dry farm store houses.',
    image: 'https://images.pexels.com/photos/3992182/pexels-photo-3992182.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-14',
    name: 'Fresh Ginger Root',
    farmerName: 'Siva Narayana',
    farmerId: 'f-7',
    farmName: 'Arogyavaram Organic Farms',
    category: 'Vegetables',
    price: 140,
    quantity: 90,
    organic: true,
    rating: 4.8,
    distance: 4.8,
    harvestDate: '2026-07-21',
    freshness: 'High',
    description: 'Spicy organic ginger root grown organically in Arogyavaram.',
    image: 'https://images.pexels.com/photos/2093444/pexels-photo-2093444.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-15',
    name: 'Organic Cucumber',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Vegetables',
    price: 25,
    quantity: 110,
    organic: true,
    rating: 4.7,
    distance: 1.5,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Hydrating organic cucumbers harvested from high-tech polyhouses.',
    image: 'https://images.pexels.com/photos/3568039/pexels-photo-3568039.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },

  // 2. Fruits (10 Items)
  {
    id: 'prod-16',
    name: 'Banginapalli Mangoes',
    farmerName: 'Venkata Ramana',
    farmerId: 'f-2',
    farmName: 'Horsley Hills Fruits',
    category: 'Fruits',
    price: 90,
    quantity: 200,
    organic: true,
    rating: 4.9,
    distance: 3.2,
    harvestDate: '2026-07-22',
    freshness: 'Excellent',
    description: 'Sweet, naturally ripened Banginapalli mangoes direct from Horsley Hills orchards.',
    image: 'https://images.pexels.com/photos/2290293/pexels-photo-2290293.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-17',
    name: 'Fresh Papaya',
    farmerName: 'Venkata Ramana',
    farmerId: 'f-2',
    farmName: 'Horsley Hills Fruits',
    category: 'Fruits',
    price: 45,
    quantity: 100,
    organic: true,
    rating: 4.6,
    distance: 3.2,
    harvestDate: '2026-07-21',
    freshness: 'High',
    description: 'Sweet table papayas harvested fresh daily.',
    image: 'https://images.pexels.com/photos/3658434/pexels-photo-3658434.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-18',
    name: 'Red Pomegranates',
    farmerName: 'Venkata Ramana',
    farmerId: 'f-2',
    farmName: 'Horsley Hills Fruits',
    category: 'Fruits',
    price: 150,
    quantity: 80,
    organic: true,
    rating: 4.8,
    distance: 3.2,
    harvestDate: '2026-07-20',
    freshness: 'High',
    description: 'Juicy ruby-red pomegranates with thin skins and sweet seeds.',
    image: 'https://images.pexels.com/photos/1435740/pexels-photo-1435740.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-19',
    name: 'Sweet Bananas (Robusta)',
    farmerName: 'Venkata Ramana',
    farmerId: 'f-2',
    farmName: 'Horsley Hills Fruits',
    category: 'Fruits',
    price: 40,
    quantity: 300,
    organic: true,
    rating: 4.5,
    distance: 3.2,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Naturally ripened Robusta bananas, sweet and pesticide-free.',
    image: 'https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-20',
    name: 'Organic Watermelon',
    farmerName: 'Bhaskar Raju',
    farmerId: 'f-10',
    farmName: 'Raju Seasonal Crops',
    category: 'Fruits',
    price: 20,
    quantity: 150,
    organic: true,
    rating: 4.7,
    distance: 9.1,
    harvestDate: '2026-07-21',
    freshness: 'Excellent',
    description: 'Juicy giant watermelons grown organically near local lake beds.',
    image: 'https://images.pexels.com/photos/1313267/pexels-photo-1313267.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-21',
    name: 'Local Guavas',
    farmerName: 'Venkata Ramana',
    farmerId: 'f-2',
    farmName: 'Horsley Hills Fruits',
    category: 'Fruits',
    price: 60,
    quantity: 90,
    organic: true,
    rating: 4.6,
    distance: 3.2,
    harvestDate: '2026-07-21',
    freshness: 'High',
    description: 'Pink-fleshed local sweet guavas harvested from orchard trees.',
    image: 'https://images.pexels.com/photos/3283626/pexels-photo-3283626.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-22',
    name: 'Custard Apple (Sitaphal)',
    farmerName: 'Venkata Ramana',
    farmerId: 'f-2',
    farmName: 'Horsley Hills Fruits',
    category: 'Fruits',
    price: 80,
    quantity: 60,
    organic: true,
    rating: 4.8,
    distance: 3.2,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Creamy custard apples hand-gathered from wild hillsides.',
    image: 'https://images.pexels.com/photos/4033282/pexels-photo-4033282.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-23',
    name: 'Green Grapes',
    farmerName: 'Venkata Ramana',
    farmerId: 'f-2',
    farmName: 'Horsley Hills Fruits',
    category: 'Fruits',
    price: 100,
    quantity: 110,
    organic: true,
    rating: 4.7,
    distance: 3.2,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Seedless crisp green grapes grown organically in Madanapalle rural.',
    image: 'https://images.pexels.com/photos/708777/pexels-photo-708777.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-24',
    name: 'Sweet Orange (Mosambi)',
    farmerName: 'Venkata Ramana',
    farmerId: 'f-2',
    farmName: 'Horsley Hills Fruits',
    category: 'Fruits',
    price: 70,
    quantity: 130,
    organic: true,
    rating: 4.5,
    distance: 3.2,
    harvestDate: '2026-07-20',
    freshness: 'High',
    description: 'Juicy mosambi oranges, perfect for immune-boosting fresh juices.',
    image: 'https://images.pexels.com/photos/2090901/pexels-photo-2090901.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-25',
    name: 'Organic Lemons (Pack of 6)',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Fruits',
    price: 20,
    quantity: 400,
    organic: true,
    rating: 4.9,
    distance: 1.5,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Highly acidic juicy lemons hand-gathered from estate trees.',
    image: 'https://images.pexels.com/photos/1414110/pexels-photo-1414110.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },

  // 3. Dairy (8 Items)
  {
    id: 'prod-26',
    name: 'Pure Cow Milk',
    farmerName: 'Gangadhar Rao',
    farmerId: 'f-5',
    farmName: 'Gangadhara Organic Dairy',
    category: 'Dairy',
    price: 60,
    quantity: 100,
    organic: true,
    rating: 4.8,
    distance: 2.1,
    harvestDate: '2026-07-22',
    freshness: 'Excellent',
    description: 'Fresh, pasteurized pure cow milk, unadulterated and full of nutrients.',
    image: 'https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-27',
    name: 'Buffalo Milk',
    farmerName: 'Gangadhar Rao',
    farmerId: 'f-5',
    farmName: 'Gangadhara Organic Dairy',
    category: 'Dairy',
    price: 70,
    quantity: 80,
    organic: true,
    rating: 4.7,
    distance: 2.1,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Thick, high-fat fresh buffalo milk suitable for paneer and curd.',
    image: 'https://images.pexels.com/photos/10125828/pexels-photo-10125828.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-28',
    name: 'A2 Cow Ghee (500ml)',
    farmerName: 'Gangadhar Rao',
    farmerId: 'f-5',
    farmName: 'Gangadhara Organic Dairy',
    category: 'Dairy',
    price: 450,
    quantity: 50,
    organic: true,
    rating: 4.9,
    distance: 2.1,
    harvestDate: '2026-07-18',
    freshness: 'High',
    description: 'Traditionally churned Vedic Bilona A2 cow ghee from local cows.',
    image: 'https://images.pexels.com/photos/10118334/pexels-photo-10118334.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-29',
    name: 'Fresh Paneer (200g)',
    farmerName: 'Gangadhar Rao',
    farmerId: 'f-5',
    farmName: 'Gangadhara Organic Dairy',
    category: 'Dairy',
    price: 90,
    quantity: 40,
    organic: true,
    rating: 4.7,
    distance: 2.1,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Soft, preservative-free fresh cottage cheese packed sanitarily.',
    image: 'https://images.pexels.com/photos/12916867/pexels-photo-12916867.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-30',
    name: 'Organic Curd (500g)',
    farmerName: 'Gangadhar Rao',
    farmerId: 'f-5',
    farmName: 'Gangadhara Organic Dairy',
    category: 'Dairy',
    price: 40,
    quantity: 60,
    organic: true,
    rating: 4.6,
    distance: 2.1,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Thick and creamy clay-pot style setting curd.',
    image: 'https://images.pexels.com/photos/5946081/pexels-photo-5946081.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-31',
    name: 'Fresh Butter (200g)',
    farmerName: 'Gangadhar Rao',
    farmerId: 'f-5',
    farmName: 'Gangadhara Organic Dairy',
    category: 'Dairy',
    price: 110,
    quantity: 30,
    organic: true,
    rating: 4.8,
    distance: 2.1,
    harvestDate: '2026-07-21',
    freshness: 'High',
    description: 'Salt-free unsalted yellow cow butter prepared using cream.',
    image: 'https://images.pexels.com/photos/920220/pexels-photo-920220.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-32',
    name: 'Spiced Buttermilk (1L)',
    farmerName: 'Gangadhar Rao',
    farmerId: 'f-5',
    farmName: 'Gangadhara Organic Dairy',
    category: 'Dairy',
    price: 30,
    quantity: 100,
    organic: true,
    rating: 4.5,
    distance: 2.1,
    harvestDate: '2026-07-22',
    freshness: 'Excellent',
    description: 'Refreshing buttermilk spiced with ginger, curry leaves, and green chillies.',
    image: 'https://images.pexels.com/photos/6027581/pexels-photo-6027581.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-33',
    name: 'Fresh Cow Milk Cream (Malai)',
    farmerName: 'Gangadhar Rao',
    farmerId: 'f-5',
    farmName: 'Gangadhara Organic Dairy',
    category: 'Dairy',
    price: 120,
    quantity: 25,
    organic: true,
    rating: 4.7,
    distance: 2.1,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Rich, thick malai gathered directly from fresh cow milk heating.',
    image: 'https://images.pexels.com/photos/8336334/pexels-photo-8336334.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },

  // 4. Grains (9 Items)
  {
    id: 'prod-34',
    name: 'Sona Masuri Rice (25kg)',
    farmerName: 'Kishore Kumar',
    farmerId: 'f-4',
    farmName: 'Ananthapuram Paddy Fields',
    category: 'Grains',
    price: 1350,
    quantity: 40,
    organic: false,
    rating: 4.7,
    distance: 6.5,
    harvestDate: '2026-06-15',
    freshness: 'High',
    description: 'Aged, lightweight long-grain sona masuri rice harvested locally.',
    image: 'https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-35',
    name: 'Organic Whole Wheat (5kg)',
    farmerName: 'Kishore Kumar',
    farmerId: 'f-4',
    farmName: 'Ananthapuram Paddy Fields',
    category: 'Grains',
    price: 240,
    quantity: 120,
    organic: true,
    rating: 4.8,
    distance: 6.5,
    harvestDate: '2026-06-20',
    freshness: 'High',
    description: 'Whole wheat grains perfect for grinding into high-fiber atta.',
    image: 'https://images.pexels.com/photos/1070058/pexels-photo-1070058.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-36',
    name: 'Finger Millet (Ragi)',
    farmerName: 'Kishore Kumar',
    farmerId: 'f-4',
    farmName: 'Ananthapuram Paddy Fields',
    category: 'Grains',
    price: 50,
    quantity: 150,
    organic: true,
    rating: 4.9,
    distance: 6.5,
    harvestDate: '2026-07-01',
    freshness: 'High',
    description: 'Calcium-rich whole ragi grains from organic Kurabalakota farm belts.',
    image: 'https://images.pexels.com/photos/59944/pexels-photo-59944.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-37',
    name: 'Pearl Millet (Sajja)',
    farmerName: 'Kishore Kumar',
    farmerId: 'f-4',
    farmName: 'Ananthapuram Paddy Fields',
    category: 'Grains',
    price: 45,
    quantity: 100,
    organic: true,
    rating: 4.6,
    distance: 6.5,
    harvestDate: '2026-07-02',
    freshness: 'High',
    description: 'Nutritious gluten-free pearl millet grains for healthy cooking.',
    image: 'https://images.pexels.com/photos/1000676/pexels-photo-1000676.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-38',
    name: 'Organic Jowar',
    farmerName: 'Kishore Kumar',
    farmerId: 'f-4',
    farmName: 'Ananthapuram Paddy Fields',
    category: 'Grains',
    price: 55,
    quantity: 140,
    organic: true,
    rating: 4.7,
    distance: 6.5,
    harvestDate: '2026-06-28',
    freshness: 'High',
    description: 'Sorghum whole grains packed with plant proteins and iron.',
    image: 'https://images.pexels.com/photos/618491/pexels-photo-618491.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-39',
    name: 'Madanapalle Groundnuts',
    farmerName: 'Mohan Babu',
    farmerId: 'f-6',
    farmName: 'Madanapalle Groundnut farm',
    category: 'Grains',
    price: 110,
    quantity: 250,
    organic: false,
    rating: 4.5,
    distance: 9.8,
    harvestDate: '2026-07-15',
    freshness: 'High',
    description: 'Sun-dried high-yield raw groundnut pods.',
    image: 'https://images.pexels.com/photos/4099354/pexels-photo-4099354.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-40',
    name: 'Cold-Pressed Peanut Oil (1L)',
    farmerName: 'Mohan Babu',
    farmerId: 'f-6',
    farmName: 'Madanapalle Groundnut farm',
    category: 'Grains',
    price: 190,
    quantity: 90,
    organic: false,
    rating: 4.8,
    distance: 9.8,
    harvestDate: '2026-07-20',
    freshness: 'Excellent',
    description: 'Wood-pressed pure peanut oil without any added chemical chemicals.',
    image: 'https://images.pexels.com/photos/33783/pexels-photo-33783.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-41',
    name: 'Organic Toor Dal',
    farmerName: 'Kishore Kumar',
    farmerId: 'f-4',
    farmName: 'Ananthapuram Paddy Fields',
    category: 'Grains',
    price: 140,
    quantity: 110,
    organic: true,
    rating: 4.8,
    distance: 6.5,
    harvestDate: '2026-07-02',
    freshness: 'High',
    description: 'Premium unpolished Toor Dal split yellow pigeon peas.',
    image: 'https://images.pexels.com/photos/8926438/pexels-photo-8926438.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-42',
    name: 'Green Gram (Moong Dal)',
    farmerName: 'Kishore Kumar',
    farmerId: 'f-4',
    farmName: 'Ananthapuram Paddy Fields',
    category: 'Grains',
    price: 120,
    quantity: 130,
    organic: true,
    rating: 4.6,
    distance: 6.5,
    harvestDate: '2026-07-05',
    freshness: 'High',
    description: 'Cleaned split green gram moong dal harvested naturally.',
    image: 'https://images.pexels.com/photos/8926451/pexels-photo-8926451.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },

  // 5. Eggs (4 Items)
  {
    id: 'prod-43',
    name: 'Country Eggs (Pack of 6)',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Eggs',
    price: 48,
    quantity: 100,
    organic: true,
    rating: 4.8,
    distance: 1.5,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Nutritious free-range country eggs from organically fed poultry.',
    image: 'https://images.pexels.com/photos/162812/pexels-photo-162812.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-44',
    name: 'Organic White Eggs (12 Pieces)',
    farmerName: 'Kishore Kumar',
    farmerId: 'f-4',
    farmName: 'Ananthapuram Paddy Fields',
    category: 'Eggs',
    price: 80,
    quantity: 150,
    organic: true,
    rating: 4.7,
    distance: 6.5,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Rich in protein, farm fresh clean eggs harvested daily.',
    image: 'https://images.pexels.com/photos/1516448/pexels-photo-1516448.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-45',
    name: 'Brown Kadaknath Eggs (6 Pieces)',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Eggs',
    price: 150,
    quantity: 50,
    organic: true,
    rating: 4.9,
    distance: 1.5,
    harvestDate: '2026-07-21',
    freshness: 'High',
    description: 'Rare premium Kadaknath black chicken eggs, highly nutritious.',
    image: 'https://images.pexels.com/photos/3971216/pexels-photo-3971216.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-46',
    name: 'Duck Eggs (6 Pieces)',
    farmerName: 'Reddy Prasad',
    farmerId: 'f-1',
    farmName: 'Madanapalle Tomato Hub',
    category: 'Eggs',
    price: 90,
    quantity: 60,
    organic: true,
    rating: 4.6,
    distance: 1.5,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Larger eggs with creamy yolks sourced from free-roaming pond ducks.',
    image: 'https://images.pexels.com/photos/5638612/pexels-photo-5638612.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },

  // 6. Flowers (4 Items)
  {
    id: 'prod-47',
    name: 'Fresh Jasmine Strings (Mallepulu)',
    farmerName: 'Radhamma Gowd',
    farmerId: 'f-8',
    farmName: 'Radha Floriculture',
    category: 'Flowers',
    price: 30,
    quantity: 200,
    organic: true,
    rating: 4.9,
    distance: 2.5,
    harvestDate: '2026-07-22',
    freshness: 'Excellent',
    description: 'Aromatic fresh local jasmine flower strings hand-tied.',
    image: 'https://images.pexels.com/photos/6231818/pexels-photo-6231818.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-48',
    name: 'Marigold Flowers (Kanakambaram/Banthi)',
    farmerName: 'Radhamma Gowd',
    farmerId: 'f-8',
    farmName: 'Radha Floriculture',
    category: 'Flowers',
    price: 50,
    quantity: 150,
    organic: true,
    rating: 4.7,
    distance: 2.5,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Bright yellow and orange marigold garlands perfect for festival decoration.',
    image: 'https://images.pexels.com/photos/1369062/pexels-photo-1369062.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-49',
    name: 'Red Roses Bunch (10 Stems)',
    farmerName: 'Radhamma Gowd',
    farmerId: 'f-8',
    farmName: 'Radha Floriculture',
    category: 'Flowers',
    price: 80,
    quantity: 80,
    organic: false,
    rating: 4.6,
    distance: 2.5,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Long-stemmed fresh red roses, harvested early morning.',
    image: 'https://images.pexels.com/photos/15239/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  },
  {
    id: 'prod-50',
    name: 'Lotus Bud Plugs (Pair)',
    farmerName: 'Radhamma Gowd',
    farmerId: 'f-8',
    farmName: 'Radha Floriculture',
    category: 'Flowers',
    price: 40,
    quantity: 50,
    organic: true,
    rating: 4.8,
    distance: 2.5,
    harvestDate: '2026-07-22',
    freshness: 'High',
    description: 'Pink sacred lotus buds gathered from freshwater ponds near Punganur.',
    image: 'https://images.pexels.com/photos/973226/pexels-photo-973226.jpeg?auto=compress&cs=tinysrgb&w=400',
    reviews: []
  }
];

export const productService = {
  getProducts: async () => {
    try {
      const response = await axiosInstance.get('/products');
      // If response is valid, return the active / available products from MongoDB
      if (response && response.data) {
        const prodList = response.data.data || response.data;
        if (Array.isArray(prodList)) {
          // Filter to show active/available products, excluding DELETED, OUT_OF_STOCK, DISABLED
          return prodList.filter(p => p.status === 'AVAILABLE' || p.status === 'ACTIVE' || !p.status);
        }
        return prodList;
      }
    } catch (err) {
      console.warn('Backend products fetch failed, using fallback mock list', err);
    }
    // Fallback Mock List
    return MOCK_PRODUCTS;
  },

  getProductById: async (id) => {
    try {
      const response = await axiosInstance.get(`/products/${id}`);
      if (response && response.data) {
        return response.data.data || response.data;
      }
    } catch (err) {
      console.warn('Backend get product by id failed, searching fallback list', err);
    }
    const product = MOCK_PRODUCTS.find(p => p.id === id);
    if (product) return product;
    throw new Error('Product not found');
  },

  searchProducts: async (query) => {
    try {
      const response = await axiosInstance.get(`/products/search?query=${query}`);
      if (response && response.data) {
        return response.data.data || response.data;
      }
    } catch (err) {
      console.warn('Backend search failed, filtering fallback list', err);
    }
    const term = query.toLowerCase();
    return MOCK_PRODUCTS.filter(p => 
      p.name.toLowerCase().includes(term) || 
      p.category.toLowerCase().includes(term) ||
      p.farmerName.toLowerCase().includes(term)
    );
  }
};

export default productService;
